# Generated by Django 5.1.2 on 2024-10-29 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('version', models.PositiveSmallIntegerField()),
                ('definition', models.JSONField()),
            ],
            options={
                'unique_together': {('type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requestor_id', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.metadataschema')),
            ],
        ),
    ]
