# Generated by Django 5.1.2 on 2024-11-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Entity'), (2, 'Batch'), (3, 'Sample'), (4, 'Result'), (5, 'Analysis')])),
                ('version', models.PositiveSmallIntegerField()),
                ('definition', models.JSONField()),
            ],
            options={
                'unique_together': {('title', 'type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.metaschema')),
                ('projects', models.ManyToManyField(related_name='entities', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField()),
                ('entities', models.ManyToManyField(related_name='batches', to='core.entity')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.metaschema')),
                ('projects', models.ManyToManyField(related_name='batches', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField()),
                ('raw_data_link', models.URLField(blank=True, help_text='Link to raw data', null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.metaschema')),
                ('projects', models.ManyToManyField(related_name='analyses', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='core.batch')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.metaschema')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.analysis')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.metaschema')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.sample')),
            ],
        ),
    ]
