# Generated by Django 5.1.2 on 2024-11-02 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetadataSchema',
            new_name='SampleSchema',
        ),
        migrations.CreateModel(
            name='EntitySchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('version', models.PositiveSmallIntegerField()),
                ('definition', models.JSONField()),
            ],
            options={
                'unique_together': {('type', 'version')},
            },
        ),
        migrations.AlterField(
            model_name='entity',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entityschema'),
        ),
    ]
